import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <DatadogInit /> */}
        <Script id="dd-rum-script">{`(function(h,o,u,n,d) {
    h=h[d]=h[d]||{q:[],onReady:function(c){h.q.push(c)}}
    d=o.createElement(u);d.async=1;d.src=n
    n=o.getElementsByTagName(u)[0];n.parentNode.insertBefore(d,n)
  })(window,document,'script','https://www.datadoghq-browser-agent.com/us1/v6/datadog-rum.js','DD_RUM')
  window.DD_RUM.onReady(function() {
    window.DD_RUM.init({
      clientToken: 'puba38a21e740329d4925829e190a10dca9',
      applicationId: '76169571-fef4-49e7-978d-88870aa6d991',
      site: 'datadoghq.com',
      service: 'todo-frontend',
      env: 'dev',
      version: '1.0.1',
      sessionSampleRate: 100,
      sessionReplaySampleRate: 100,
      trackUserInteractions: true,
      trackResources: true,
      trackLongTasks: true,
      defaultPrivacyLevel: 'mask-user-input',    
      allowedTracingUrls: [
        'http:\/\/localhost:8000',
        'http:\/\/localhost:8000/notes',
        'http:\/\/localhost:5000',
        'http:\/\/35\.190\.120\.223\/api',
        'http:\/\/35\.190\.120\.223\/api\/notes',
        'https:\/\/backend-service:5000',
        'https:\/\/backend-service:8000',
      ],
    });
  })`}</Script>
        {children}
      </body>
    </html>
  );
}
