apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "notes-db"
        - name: DD_VERSION
          value: "0.2"
        - name: POSTGRES_DB
          value: "notesdb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres-password
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-script 